kind: pipeline
type: exec
name: kwebPM

platform:
  os: linux
  arch: amd64

steps:
- name: greeting
  commands:
  - docker build -t kwebpm .
  - docker stop kwebpm
  - docker volume create kwebpmvolume
  - docker run --name kwebpm -v kwebpmvolume:/app/data -p 90:90 kwebpm