kind: pipeline
type: exec
name: kwebPM

platform:
  os: linux
  arch: amd64

steps:
- name: build and publish
  commands:
  - docker build -t kwebpm .
  - docker stop kwebpm || true
  - docker volume create kwebpmvolume || true
  - docker run --name kwebpm -v kwebpmvolume:/app/data -p 90:90 kwebpm