kind: pipeline
type: exec
name: kwebPM

platform:
  os: linux
  arch: amd64

steps:
- name: greeting
  commands:
  - docker build -t $IMAGE_NAME .
  - docker stop $IMAGE_NAME
  - docker volume create $VOLUME_NAME
  - docker run --name $IMAGE_NAME -v $VOLUME_NAME:/app/data -p $PORT $IMAGE_NAME
  enviroment:
    IMAGE_NAME: kwebpm
    VOLUME_NAME: kwebpmvolume
    PORT: 90:90