kind: pipeline
type: exec
name: kwebPM

platform:
  os: linux
  arch: amd64

steps:
- name: greeting
  commands:
  - docker build -t $DRONE_REPO_NAME .
  - docker stop $DRONE_REPO_NAME
  - docker volume create $DRONE_REPO_NAME
  - docker run --name $DRONE_REPO_NAME -v $DRONE_REPO_NAME:/app/data -p 90:90 $DRONE_REPO_NAME